# Generated by Django 6.1.1 on 2026-09-25 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lawyers", "0002_seed_pakistan_bar_councils"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "lawyer_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="lawyers.lawyerprofile",
                    ),
                ),
                (
                    "lawyer_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="lawyers.lawyerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "connection",
                "verbose_name_plural": "connections",
                "indexes": [models.Index(fields=["lawyer_b"], name="network_conn_lawyer_b_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lawyer_a", "lawyer_b"),
                        name="network_one_connection_per_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lawyer_a__lt", models.F("lawyer_b"))),
                        name="network_connection_ordered_pair",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConnectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to="lawyers.lawyerprofile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_requests",
                        to="lawyers.lawyerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "connection request",
                "verbose_name_plural": "connection requests",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sender", "recipient"),
                        name="network_one_request_per_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sender", models.F("recipient")), _negated=True),
                        name="network_no_self_request",
                    ),
                ],
            },
        ),
    ]
