# Generated by Django 6.1.1 on 2026-09-25 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=30, unique=True, verbose_name="code"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "country",
                    models.CharField(default="PK", max_length=2, verbose_name="country code"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "jurisdiction",
                "verbose_name_plural": "jurisdictions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LawyerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "headline",
                    models.CharField(blank=True, max_length=160, verbose_name="headline"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="bio")),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="city"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lawyer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "lawyer profile",
                "verbose_name_plural": "lawyer profiles",
            },
        ),
        migrations.CreateModel(
            name="BarAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "license_number",
                    models.CharField(max_length=50, verbose_name="license number"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="reviewed at"),
                ),
                (
                    "rejection_reason",
                    models.CharField(blank=True, max_length=255, verbose_name="rejection reason"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lawyers.jurisdiction",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="lawyers.lawyerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "bar admission",
                "verbose_name_plural": "bar admissions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lawyer", "jurisdiction"),
                        name="lawyers_one_admission_per_jurisdiction",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "verified")),
                        fields=("jurisdiction", "license_number"),
                        name="lawyers_unique_verified_license",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "pending"),
                            ("reviewed_at__isnull", False),
                            _connector="OR",
                        ),
                        name="lawyers_reviewed_admission_has_timestamp",
                    ),
                ],
            },
        ),
    ]
