# Generated by Django 6.1.1 on 2026-09-25 05:24

from django.db import migrations

PAKISTAN_BAR_COUNCILS = [
    ("pk-pbc", "Pakistan Bar Council"),
    ("pk-punjab", "Punjab Bar Council"),
    ("pk-sindh", "Sindh Bar Council"),
    ("pk-kp", "Khyber Pakhtunkhwa Bar Council"),
    ("pk-balochistan", "Balochistan Bar Council"),
    ("pk-islamabad", "Islamabad Bar Council"),
]


def seed(apps, schema_editor):
    Jurisdiction = apps.get_model("lawyers", "Jurisdiction")
    for code, name in PAKISTAN_BAR_COUNCILS:
        Jurisdiction.objects.update_or_create(code=code, defaults={"name": name, "country": "PK"})


def unseed(apps, schema_editor):
    Jurisdiction = apps.get_model("lawyers", "Jurisdiction")
    Jurisdiction.objects.filter(code__in=[code for code, _ in PAKISTAN_BAR_COUNCILS]).delete()


class Migration(migrations.Migration):
    dependencies = [("lawyers", "0001_initial")]

    operations = [migrations.RunPython(seed, unseed)]
